#!/usr/bin/env swift

/// Script to move icons from a folder of this repository to the assets
/// Direct execution
/// ```./.script/generate-iconography-codebase.swift```
/// Or
/// ```swift .script/generate-iconography-codebase.swift```

import Foundation

// MARK: - Models

fileprivate struct IconCategory {
    let name: String
    let icons: [String]
}

// MARK: - Helpers

private func toCamelCase(_ string: String) -> String {
    guard !string.isEmpty else { return string }

    // Handle special cases
    let specialCases = ["3D": "threeD", "360": "threeSixty"]
    if let specialCase = specialCases[string] {
        return specialCase
    }

    // Convert "AddCircleFill" -> "addCircleFill"
    let firstChar = string.prefix(1).lowercased()
    let rest = string.dropFirst()
    return firstChar + rest
}

private func isReservedKeyword(_ word: String) -> Bool {
    let keywords = ["class", "do", "import"]
    return keywords.contains(word.lowercased())
}

private func sanitizeName(_ name: String) -> String {
    if isReservedKeyword(name) {
        return "`\(name)`"
    }
    return name
}

// MARK: - File System Operations

private func findIconCategories(at path: String) -> [IconCategory] {
    let fileManager = FileManager.default
    var categories: [IconCategory] = []

    guard let enumerator = fileManager.enumerator(
        at: URL(fileURLWithPath: path),
        includingPropertiesForKeys: [.isDirectoryKey],
        options: [.skipsHiddenFiles]
    ) else {
        print("Error: Cannot enumerate directory at \(path)")
        return []
    }

    var categoryDict: [String: [String]] = [:]

    for case let fileURL as URL in enumerator {
        guard let resourceValues = try? fileURL.resourceValues(forKeys: [.isDirectoryKey]),
              let isDirectory = resourceValues.isDirectory,
              isDirectory,
              fileURL.lastPathComponent.hasSuffix(".imageset") else {
            continue
        }

        // Get category name (parent folder)
        let categoryName = fileURL.deletingLastPathComponent().lastPathComponent

        // Skip if it's the root or Contents.json
        guard categoryName != "Iconography.xcassets" && categoryName != "Contents.json" else {
            continue
        }

        // Get icon name (without .imageset)
        let iconName = fileURL.lastPathComponent.replacingOccurrences(of: ".imageset", with: "")

        if categoryDict[categoryName] == nil {
            categoryDict[categoryName] = []
        }
        categoryDict[categoryName]?.append(iconName)
    }

    // Convert to IconCategory array and sort
    for (categoryName, icons) in categoryDict {
        let sortedIcons = icons.sorted()
        categories.append(IconCategory(name: categoryName, icons: sortedIcons))
    }

    return categories.sorted { $0.name < $1.name }
}

// MARK: - Resources Code Generation

private func getCategoryEnumName(category: String) -> String {
    // Map category names to enum names
    switch category {
    case "Global":
        return "Spark"
    case "Criteria":
        return "SparkCriteria"
    default:
        return "Spark\(category)"
    }
}

private func generateCategoryEnum(category: IconCategory) -> String {
    let enumName = getCategoryEnumName(category: category.name)
    var output = "    enum \(enumName) {\n"

    // Generate static properties for each icon
    for icon in category.icons {
        let propertyName = sanitizeName(toCamelCase(icon))
        output += "        public static let \(propertyName) = ImageResource(name: \"\(category.name)/\(icon)\", bundle: .current)\n"
    }

    output += "    }\n"

    return output
}

private func generateIconographyFile(categories: [IconCategory]) -> String {
    var output = "// swiftlint:disable all\n"
    output += "// Generated using generate-iconography-codebase.swift\n"
    output += "// DO NOT EDIT - This file is automatically generated\n\n"
    output += "import DeveloperToolsSupport\n\n"
    output += "// swiftlint:disable all\n"
    output += "public extension ImageResource {\n\n"

    // Generate category enums
    for (index, category) in categories.enumerated() {
        output += generateCategoryEnum(category: category)
        if index < categories.count - 1 {
            output += "\n"
        }
    }

    output += "}\n"

    return output
}

private func writeIconographyFile(categories: [IconCategory], outputPath: String, outputFile: String) {
    // Generate code
    print("\n💻 Generating Swift code...")
    let generatedCode = generateIconographyFile(categories: categories)

    // Create output directory if needed
    do {
        try FileManager.default.createDirectory(
            atPath: outputPath,
            withIntermediateDirectories: true,
            attributes: nil
        )
    } catch {
        print("❌ Error creating output directory: \(error)")
        exit(1)
    }

    // Write to file
    do {
        try generatedCode.write(toFile: outputFile, atomically: true, encoding: .utf8)
        print("✅ Successfully generated: \(outputFile)")
    } catch {
        print("❌ Error writing file: \(error)")
        exit(1)
    }
}

// MARK: - Demo Code Generation

private func generateDemoCaseIterableEnum(category: IconCategory, enumName: String) -> String {
    // Determine the ImageResource enum name
    let imageResourceEnumName = getCategoryEnumName(category: category.name)

    var output = "// swiftlint:disable all\n"
    output += "public enum \(enumName): String, CaseIterable {\n"

    // Generate cases for each icon
    for icon in category.icons {
        let caseName = sanitizeName(toCamelCase(icon))
        output += "    case \(caseName)\n"
    }

    // Add computed property for ImageResource
    output += "\n"
    output += "    // MARK: - Properties\n"
    output += "\n"
    output += "    public var imageResource: ImageResource {\n"
    output += "        return switch self {\n"

    for icon in category.icons {
        let caseName = sanitizeName(toCamelCase(icon))
        output += "        case .\(caseName): .\(imageResourceEnumName).\(caseName)\n"
    }

    output += "        }\n"
    output += "    }\n"
    output += "}\n"

    return output
}

private func generateCombinedDemoFile(categories: [IconCategory]) -> String {
    var output = "// swiftlint:disable all\n"
    output += "// Generated using generate-iconography-codebase.swift\n"
    output += "// DO NOT EDIT - This file is automatically generated\n\n"
    output += "import DeveloperToolsSupport\n\n"

    // Generate enums for each category
    for (index, category) in categories.enumerated() {
        var enumName: String?

        switch category.name {
        case "Global":
            enumName = "Iconography"
        case "Criteria":
            enumName = "CriteriaIconography"
        default:
            continue // Skip other categories
        }

        if let name = enumName {
            output += "// MARK: - \(name)\n\n"
            output += generateDemoCaseIterableEnum(category: category, enumName: name)

            // Add spacing between enums
            if index < categories.count - 1 {
                output += "\n"
            }
        }
    }

    return output
}

private func writeDemoFiles(categories: [IconCategory], currentDirectory: String) {
    let demoOutputPath = "\(currentDirectory)/Demo/Sources/Iconography"
    let combinedDemoFile = "\(demoOutputPath)/Iconography+Generated.swift"

    // Create demo output directory if needed
    do {
        try FileManager.default.createDirectory(
            atPath: demoOutputPath,
            withIntermediateDirectories: true,
            attributes: nil
        )
    } catch {
        print("❌ Error creating demo output directory: \(error)")
        exit(1)
    }

    // Generate combined demo file
    print("\n💻 Generating combined demo file...")
    let combinedDemoCode = generateCombinedDemoFile(categories: categories)

    do {
        try combinedDemoCode.write(toFile: combinedDemoFile, atomically: true, encoding: .utf8)
        print("✅ Successfully generated: \(combinedDemoFile)")
    } catch {
        print("❌ Error writing combined demo file: \(error)")
        exit(1)
    }

    // Clean up old separate files if they exist
    let oldFiles = ["GlobalIconography.swift", "CriteriaIconography.swift"]
    for oldFile in oldFiles {
        let oldFilePath = "\(demoOutputPath)/\(oldFile)"
        if FileManager.default.fileExists(atPath: oldFilePath) {
            do {
                try FileManager.default.removeItem(atPath: oldFilePath)
                print("🗑️  Removed old file: \(oldFile)")
            } catch {
                print("⚠️  Warning: Could not remove old file \(oldFile): \(error)")
            }
        }
    }
}

// MARK: - Main

func main() {
    print("🚀 Starting Iconography generation...")

    let currentDirectory = FileManager.default.currentDirectoryPath
    let iconographyPath = "\(currentDirectory)/Resources/Sources/Core/Assets/Iconography.xcassets"
    let outputPath = "\(currentDirectory)/Resources/Sources/Core/Extension"
    let outputFile = "\(outputPath)/ImageResource+IconographyGenerated.swift"

    // Check if iconography directory exists
    guard FileManager.default.fileExists(atPath: iconographyPath) else {
        print("❌ Error: Iconography.xcassets not found at \(iconographyPath)")
        exit(1)
    }

    // Find all icon categories
    print("📂 Scanning for icon categories...")
    let categories = findIconCategories(at: iconographyPath)

    guard !categories.isEmpty else {
        print("❌ Error: No icon categories found")
        exit(1)
    }

    print("✅ Found \(categories.count) categories:")
    for category in categories {
        print("  - \(category.name): \(category.icons.count) icons")
    }

    // Generate and write iconography file
    writeIconographyFile(categories: categories, outputPath: outputPath, outputFile: outputFile)

    // Generate combined demo files
    writeDemoFiles(categories: categories, currentDirectory: currentDirectory)

    print("\n🎉 Done!")
}

main()
