// swiftlint:disable all
// Generated using generate-iconography-codebase.swift
// DO NOT EDIT - This file is automatically generated

import DeveloperToolsSupport

// MARK: - CriteriaIconography

// swiftlint:disable all
public enum CriteriaIconography: String, CaseIterable {
    case babyBed
    case babyBottle
    case balcony
    case barrow
    case bathtub
    case bear
    case bed
    case bell
    case bicycle
    case bikeSize
    case bird
    case birthdayCake
    case bluetooth
    case boat
    case book
    case box
    case brand
    case briefcase
    case buildings
    case calendar
    case carBattery
    case carCloseup
    case carType
    case cave
    case circleWeight
    case `class`
    case clock
    case closure
    case coffee
    case commonHouse
    case compass
    case controller
    case coverage
    case cutlery
    case cylindrical
    case diamond
    case digicode
    case doorsCar
    case dumbbell
    case dumpTruck
    case duplex
    case electricalSocket
    case energy
    case engineCar
    case euros
    case excavator
    case fabric
    case family
    case fireplace
    case flower
    case foot
    case fuel
    case furniture
    case furnitureType
    case garage
    case garden
    case glassWindows
    case gps
    case graphic
    case groundFloor
    case handCat
    case handDelivered
    case handGift
    case headlight
    case headsCat
    case headsDog
    case houseQuestion
    case interphone
    case jewels
    case keylessAccess
    case lastFloor
    case license
    case lift
    case like
    case linens
    case listing
    case localisation
    case loft
    case loggia
    case lotusFlower
    case manUniform
    case manorHouse
    case materials
    case measures
    case medal
    case meter
    case metro
    case microchipPet
    case mileage
    case mobile
    case mobileQuestion
    case moto
    case moulding
    case mouseComputer
    case paintPalette
    case paperJob
    case paperProperty
    case parkAssist
    case parking
    case parkingSensor
    case parquet
    case paw
    case pencilDocuments
    case people
    case person
    case petAccessory
    case photoFrame
    case plan
    case plumbingElectrical
    case pool
    case power
    case rainSensor
    case rearviewCamera
    case seaView
    case seatCar
    case seatsCar
    case serringue
    case shoes
    case shovelRake
    case shower
    case simCard
    case smoking
    case snowflake
    case sort
    case speaker
    case speed
    case speedIndicator
    case sprayer
    case stairs
    case starHouse
    case stars
    case state
    case sticker
    case store
    case studentHat
    case sun
    case sunroof
    case terrace
    case timer
    case tools
    case towel
    case tractor
    case truck
    case trunkCar
    case tshirtShort
    case tv
    case view
    case wardrobe
    case washingMachine
    case wc
    case weight
    case wheelRim
    case wifi
    case woodenDoor

    // MARK: - Properties

    public var imageResource: ImageResource {
        return switch self {
        case .babyBed: .SparkCriteria.babyBed
        case .babyBottle: .SparkCriteria.babyBottle
        case .balcony: .SparkCriteria.balcony
        case .barrow: .SparkCriteria.barrow
        case .bathtub: .SparkCriteria.bathtub
        case .bear: .SparkCriteria.bear
        case .bed: .SparkCriteria.bed
        case .bell: .SparkCriteria.bell
        case .bicycle: .SparkCriteria.bicycle
        case .bikeSize: .SparkCriteria.bikeSize
        case .bird: .SparkCriteria.bird
        case .birthdayCake: .SparkCriteria.birthdayCake
        case .bluetooth: .SparkCriteria.bluetooth
        case .boat: .SparkCriteria.boat
        case .book: .SparkCriteria.book
        case .box: .SparkCriteria.box
        case .brand: .SparkCriteria.brand
        case .briefcase: .SparkCriteria.briefcase
        case .buildings: .SparkCriteria.buildings
        case .calendar: .SparkCriteria.calendar
        case .carBattery: .SparkCriteria.carBattery
        case .carCloseup: .SparkCriteria.carCloseup
        case .carType: .SparkCriteria.carType
        case .cave: .SparkCriteria.cave
        case .circleWeight: .SparkCriteria.circleWeight
        case .`class`: .SparkCriteria.`class`
        case .clock: .SparkCriteria.clock
        case .closure: .SparkCriteria.closure
        case .coffee: .SparkCriteria.coffee
        case .commonHouse: .SparkCriteria.commonHouse
        case .compass: .SparkCriteria.compass
        case .controller: .SparkCriteria.controller
        case .coverage: .SparkCriteria.coverage
        case .cutlery: .SparkCriteria.cutlery
        case .cylindrical: .SparkCriteria.cylindrical
        case .diamond: .SparkCriteria.diamond
        case .digicode: .SparkCriteria.digicode
        case .doorsCar: .SparkCriteria.doorsCar
        case .dumbbell: .SparkCriteria.dumbbell
        case .dumpTruck: .SparkCriteria.dumpTruck
        case .duplex: .SparkCriteria.duplex
        case .electricalSocket: .SparkCriteria.electricalSocket
        case .energy: .SparkCriteria.energy
        case .engineCar: .SparkCriteria.engineCar
        case .euros: .SparkCriteria.euros
        case .excavator: .SparkCriteria.excavator
        case .fabric: .SparkCriteria.fabric
        case .family: .SparkCriteria.family
        case .fireplace: .SparkCriteria.fireplace
        case .flower: .SparkCriteria.flower
        case .foot: .SparkCriteria.foot
        case .fuel: .SparkCriteria.fuel
        case .furniture: .SparkCriteria.furniture
        case .furnitureType: .SparkCriteria.furnitureType
        case .garage: .SparkCriteria.garage
        case .garden: .SparkCriteria.garden
        case .glassWindows: .SparkCriteria.glassWindows
        case .gps: .SparkCriteria.gps
        case .graphic: .SparkCriteria.graphic
        case .groundFloor: .SparkCriteria.groundFloor
        case .handCat: .SparkCriteria.handCat
        case .handDelivered: .SparkCriteria.handDelivered
        case .handGift: .SparkCriteria.handGift
        case .headlight: .SparkCriteria.headlight
        case .headsCat: .SparkCriteria.headsCat
        case .headsDog: .SparkCriteria.headsDog
        case .houseQuestion: .SparkCriteria.houseQuestion
        case .interphone: .SparkCriteria.interphone
        case .jewels: .SparkCriteria.jewels
        case .keylessAccess: .SparkCriteria.keylessAccess
        case .lastFloor: .SparkCriteria.lastFloor
        case .license: .SparkCriteria.license
        case .lift: .SparkCriteria.lift
        case .like: .SparkCriteria.like
        case .linens: .SparkCriteria.linens
        case .listing: .SparkCriteria.listing
        case .localisation: .SparkCriteria.localisation
        case .loft: .SparkCriteria.loft
        case .loggia: .SparkCriteria.loggia
        case .lotusFlower: .SparkCriteria.lotusFlower
        case .manUniform: .SparkCriteria.manUniform
        case .manorHouse: .SparkCriteria.manorHouse
        case .materials: .SparkCriteria.materials
        case .measures: .SparkCriteria.measures
        case .medal: .SparkCriteria.medal
        case .meter: .SparkCriteria.meter
        case .metro: .SparkCriteria.metro
        case .microchipPet: .SparkCriteria.microchipPet
        case .mileage: .SparkCriteria.mileage
        case .mobile: .SparkCriteria.mobile
        case .mobileQuestion: .SparkCriteria.mobileQuestion
        case .moto: .SparkCriteria.moto
        case .moulding: .SparkCriteria.moulding
        case .mouseComputer: .SparkCriteria.mouseComputer
        case .paintPalette: .SparkCriteria.paintPalette
        case .paperJob: .SparkCriteria.paperJob
        case .paperProperty: .SparkCriteria.paperProperty
        case .parkAssist: .SparkCriteria.parkAssist
        case .parking: .SparkCriteria.parking
        case .parkingSensor: .SparkCriteria.parkingSensor
        case .parquet: .SparkCriteria.parquet
        case .paw: .SparkCriteria.paw
        case .pencilDocuments: .SparkCriteria.pencilDocuments
        case .people: .SparkCriteria.people
        case .person: .SparkCriteria.person
        case .petAccessory: .SparkCriteria.petAccessory
        case .photoFrame: .SparkCriteria.photoFrame
        case .plan: .SparkCriteria.plan
        case .plumbingElectrical: .SparkCriteria.plumbingElectrical
        case .pool: .SparkCriteria.pool
        case .power: .SparkCriteria.power
        case .rainSensor: .SparkCriteria.rainSensor
        case .rearviewCamera: .SparkCriteria.rearviewCamera
        case .seaView: .SparkCriteria.seaView
        case .seatCar: .SparkCriteria.seatCar
        case .seatsCar: .SparkCriteria.seatsCar
        case .serringue: .SparkCriteria.serringue
        case .shoes: .SparkCriteria.shoes
        case .shovelRake: .SparkCriteria.shovelRake
        case .shower: .SparkCriteria.shower
        case .simCard: .SparkCriteria.simCard
        case .smoking: .SparkCriteria.smoking
        case .snowflake: .SparkCriteria.snowflake
        case .sort: .SparkCriteria.sort
        case .speaker: .SparkCriteria.speaker
        case .speed: .SparkCriteria.speed
        case .speedIndicator: .SparkCriteria.speedIndicator
        case .sprayer: .SparkCriteria.sprayer
        case .stairs: .SparkCriteria.stairs
        case .starHouse: .SparkCriteria.starHouse
        case .stars: .SparkCriteria.stars
        case .state: .SparkCriteria.state
        case .sticker: .SparkCriteria.sticker
        case .store: .SparkCriteria.store
        case .studentHat: .SparkCriteria.studentHat
        case .sun: .SparkCriteria.sun
        case .sunroof: .SparkCriteria.sunroof
        case .terrace: .SparkCriteria.terrace
        case .timer: .SparkCriteria.timer
        case .tools: .SparkCriteria.tools
        case .towel: .SparkCriteria.towel
        case .tractor: .SparkCriteria.tractor
        case .truck: .SparkCriteria.truck
        case .trunkCar: .SparkCriteria.trunkCar
        case .tshirtShort: .SparkCriteria.tshirtShort
        case .tv: .SparkCriteria.tv
        case .view: .SparkCriteria.view
        case .wardrobe: .SparkCriteria.wardrobe
        case .washingMachine: .SparkCriteria.washingMachine
        case .wc: .SparkCriteria.wc
        case .weight: .SparkCriteria.weight
        case .wheelRim: .SparkCriteria.wheelRim
        case .wifi: .SparkCriteria.wifi
        case .woodenDoor: .SparkCriteria.woodenDoor
        }
    }
}

// MARK: - Iconography

// swiftlint:disable all
public enum Iconography: String, CaseIterable {
    case babyBottle
    case ball
    case bannedFill
    case bannedOutline
    case bedFill
    case bedLinen
    case bedOutline
    case bellFill
    case bellOffFill
    case bellOffOutline
    case bellOnFill
    case bellOnOutline
    case bellOutline
    case bellShakeFill
    case bellShakeOutline
    case bike
    case bodySuit
    case book
    case bookmarkFill
    case bookmarkOutline
    case boxFill
    case boxOutline
    case boxes
    case briefcase
    case broomstick
    case bubbleChatFill
    case bubbleChatOutline
    case bubbleCheck
    case bubbleDotsFill
    case bubbleDotsOutline
    case bubbleLightning
    case bubbleTextFill
    case bubbleTextOutline
    case bubbleWarningFill
    case bubbleWarningOutline
    case building
    case buildingCircle
    case buildingSquare
    case burgerMenu
    case calculatorFill
    case calculatorOutline
    case calendarCheckFill
    case calendarCheckOutline
    case calendarDotFill
    case calendarDotOutline
    case calendarTextFill
    case calendarTextOutline
    case cameraAI
    case cameraFill
    case cameraLens
    case cameraOutline
    case cameraVideo
    case camper
    case carFill
    case carOutline
    case carWarrantyFill
    case carWarrantyOutline
    case cardBoard
    case cardBrand
    case chain
    case check
    case chevronHorizontalDown
    case chevronHorizontalUp
    case chevronVerticalLeft
    case chevronVerticalRight
    case circleCheckFill
    case circleCheckOutline
    case circleCrossFill
    case circleCrossOutline
    case clickCursorFill
    case clickCursorOutline
    case clockArrow
    case clockFill
    case clockOutline
    case coinsFill
    case coinsOutline
    case computer
    case connectedWatch
    case controller
    case copyFill
    case copyOutline
    case couch
    case cradle
    case creditCardFill
    case creditCardOutline
    case critair
    case crop
    case cross
    case cursorFill
    case cursorOutline
    case deliveryBoxFill
    case deliveryBoxOutline
    case deliveryHandsFill
    case deliveryHandsOutline
    case deliveryTruckFill
    case deliveryTruckOutline
    case disconnect
    case dissatisfiedFaceFill
    case dissatisfiedFaceOutline
    case doubleCheck
    case doubleChevronsLeft
    case doubleChevronsRight
    case downloadFileFill
    case downloadFileOutline
    case dress
    case electricalPlug
    case euroShieldFill
    case euroShieldOutline
    case euroSymbol
    case export
    case eyeFill
    case eyeOffFill
    case eyeOffOutline
    case eyeOutline
    case facebookLogoFill
    case facebookLogoOutline
    case family
    case fileFill
    case fileOffFill
    case fileOffOutline
    case fileOutline
    case filter
    case fireFill
    case fireOutline
    case flagFill
    case flagOutline
    case flashlightFill
    case flashlightOutline
    case floorPlan
    case foldedEnvelopFill
    case foldedEnvelopOutline
    case forwardFill
    case forwardOutline
    case fountainPen
    case franceFill
    case franceOutline
    case galleryFill
    case galleryOutline
    case gameBoy
    case garage
    case gardenTools
    case gearFill
    case gearOutline
    case gift
    case grapes
    case graphArrowDown
    case graphArrowUp
    case graphFill
    case graphOutline
    case graphicCursor
    case graphicHand
    case groupFill
    case groupOutline
    case guitar
    case handGift
    case happyFaceFill
    case happyFaceOutline
    case headphoneFill
    case headphoneOutline
    case headphoneSmileFill
    case headphoneSmileOutline
    case heartFill
    case heartHandshake
    case heartOutline
    case heatingHouse
    case highlight
    case homeCheckFill
    case homeCheckOutline
    case homeFill
    case homeOutline
    case hotWaterdrop
    case house
    case identityCardFill
    case identityCardOutline
    case imageFill
    case imageOutline
    case `import`
    case infoFill
    case infoOutline
    case instagramLogoFill
    case instagramLogoOutline
    case keyFill
    case keyHouse
    case keyOutline
    case lamp
    case largeArrowUpFill
    case largeArrowUpOutline
    case layerFill
    case layerOutline
    case letterDotFill
    case letterDotOutline
    case letterFill
    case letterOutline
    case lightBulbFill
    case lightBulbOutline
    case lightningFill
    case lightningOutline
    case linkedinLogo
    case list
    case listItemSelected
    case lockFill
    case lockOutline
    case lockerFill
    case lockerOutline
    case luggages
    case magnifierCrossFill
    case magnifierCrossOutline
    case magnifierFill
    case magnifierOutline
    case magnifierScan
    case mailBoxCloseFill
    case mailBoxCloseOutline
    case mailBoxOpenFill
    case mailBoxOpenOutline
    case manWalkingFill
    case manWalkingOutline
    case maternity
    case medal
    case megaphoneFill
    case megaphoneMuteFill
    case megaphoneMuteOutline
    case megaphoneOutline
    case messengerLogo
    case microphoneAI
    case microphoneFill
    case microphoneOffFill
    case microphoneOffOutline
    case microphoneOutline
    case microwave
    case minus
    case minusCircleFill
    case minusCircleOutline
    case mobile
    case mobileCheck
    case monumentFill
    case monumentOutline
    case moonStar
    case motorBike
    case mouse
    case moveUp
    case movie
    case multimedia
    case multimediaSystem
    case music
    case musician
    case neutralFaceFill
    case neutralFaceOutline
    case oldFill
    case oldOutline
    case openLetterFill
    case openLetterOutline
    case paintPalette
    case paintbrushAI
    case paperMapFill
    case paperMapOutline
    case parasolFill
    case parasolOutline
    case pawn
    case pdfFill
    case pdfOutline
    case penFill
    case penOutline
    case percentage
    case petPaw
    case phoneCallEnterFill
    case phoneCallEnterOutline
    case phoneCallFill
    case phoneCallMissFill
    case phoneCallMissOutline
    case phoneCallOutline
    case phoneCallSuccessFill
    case phoneCallSuccessOutline
    case phoneFill
    case phoneOutline
    case photoPack
    case piggyBankFill
    case piggyBankOutline
    case pinFill
    case pinOutline
    case pinterestLogo
    case placeholder
    case plant
    case playFill
    case playOutline
    case plus
    case premiumFill
    case premiumOutline
    case printerFill
    case printerOutline
    case profileFill
    case profileOutline
    case pyramid
    case qRCodeScan
    case questionFill
    case questionOutline
    case rearviewmirror
    case redoArrow
    case refresh
    case refundEuro
    case rocketFill
    case rocketOutline
    case rotateImage
    case sadFaceFill
    case sadFaceOutline
    case sailboat
    case sandglassFill
    case sandglassOutline
    case scan
    case schoolBag
    case shareExternal
    case shareFill
    case shareOutline
    case shareiOs
    case shinyBuildings
    case shoes
    case shoppingCartFill
    case shoppingCartOutline
    case sort
    case sparks
    case speedmeterFill
    case speedmeterOutline
    case stack
    case starFill
    case starOutline
    case stopFill
    case stopOutline
    case stoplight
    case storeFill
    case storeOutline
    case strokeImage
    case stroller
    case studentHat
    case sun
    case sunMoon
    case sunnyHouse
    case tablet
    case tableware
    case tagFill
    case tagOutline
    case targetFill
    case targetOutline
    case teddyBear
    case threeDimension
    case threeDimension_2
    case threeDotsHorizontal
    case threeDotsVertical
    case threeSixty
    case thumbDownFill
    case thumbDownOutline
    case thumbUpFill
    case thumbUpOutline
    case thumbtack
    case ticket
    case tractor
    case trainFill
    case trainOutline
    case trashCrossFill
    case trashCrossOutline
    case trashFill
    case trashOutline
    case treeFence
    case truckClockFill
    case truckClockOutline
    case tshirt
    case twitterLogo
    case undoArrow
    case unlockFill
    case unlockOutline
    case userCheckFill
    case userCheckOutline
    case userCircleFill
    case userCircleOutline
    case userFill
    case userOutline
    case utilityTruck
    case vase
    case verifiedShieldFill
    case verifiedShieldOutline
    case walletBrand
    case warningFill
    case warningImage
    case warningOutline
    case warningShieldFill
    case warningShieldOutline
    case watch
    case waterdrop
    case whatsappLogo
    case wifi
    case workFill
    case workOutline
    case wrench

    // MARK: - Properties

    public var imageResource: ImageResource {
        return switch self {
        case .babyBottle: .Spark.babyBottle
        case .ball: .Spark.ball
        case .bannedFill: .Spark.bannedFill
        case .bannedOutline: .Spark.bannedOutline
        case .bedFill: .Spark.bedFill
        case .bedLinen: .Spark.bedLinen
        case .bedOutline: .Spark.bedOutline
        case .bellFill: .Spark.bellFill
        case .bellOffFill: .Spark.bellOffFill
        case .bellOffOutline: .Spark.bellOffOutline
        case .bellOnFill: .Spark.bellOnFill
        case .bellOnOutline: .Spark.bellOnOutline
        case .bellOutline: .Spark.bellOutline
        case .bellShakeFill: .Spark.bellShakeFill
        case .bellShakeOutline: .Spark.bellShakeOutline
        case .bike: .Spark.bike
        case .bodySuit: .Spark.bodySuit
        case .book: .Spark.book
        case .bookmarkFill: .Spark.bookmarkFill
        case .bookmarkOutline: .Spark.bookmarkOutline
        case .boxFill: .Spark.boxFill
        case .boxOutline: .Spark.boxOutline
        case .boxes: .Spark.boxes
        case .briefcase: .Spark.briefcase
        case .broomstick: .Spark.broomstick
        case .bubbleChatFill: .Spark.bubbleChatFill
        case .bubbleChatOutline: .Spark.bubbleChatOutline
        case .bubbleCheck: .Spark.bubbleCheck
        case .bubbleDotsFill: .Spark.bubbleDotsFill
        case .bubbleDotsOutline: .Spark.bubbleDotsOutline
        case .bubbleLightning: .Spark.bubbleLightning
        case .bubbleTextFill: .Spark.bubbleTextFill
        case .bubbleTextOutline: .Spark.bubbleTextOutline
        case .bubbleWarningFill: .Spark.bubbleWarningFill
        case .bubbleWarningOutline: .Spark.bubbleWarningOutline
        case .building: .Spark.building
        case .buildingCircle: .Spark.buildingCircle
        case .buildingSquare: .Spark.buildingSquare
        case .burgerMenu: .Spark.burgerMenu
        case .calculatorFill: .Spark.calculatorFill
        case .calculatorOutline: .Spark.calculatorOutline
        case .calendarCheckFill: .Spark.calendarCheckFill
        case .calendarCheckOutline: .Spark.calendarCheckOutline
        case .calendarDotFill: .Spark.calendarDotFill
        case .calendarDotOutline: .Spark.calendarDotOutline
        case .calendarTextFill: .Spark.calendarTextFill
        case .calendarTextOutline: .Spark.calendarTextOutline
        case .cameraAI: .Spark.cameraAI
        case .cameraFill: .Spark.cameraFill
        case .cameraLens: .Spark.cameraLens
        case .cameraOutline: .Spark.cameraOutline
        case .cameraVideo: .Spark.cameraVideo
        case .camper: .Spark.camper
        case .carFill: .Spark.carFill
        case .carOutline: .Spark.carOutline
        case .carWarrantyFill: .Spark.carWarrantyFill
        case .carWarrantyOutline: .Spark.carWarrantyOutline
        case .cardBoard: .Spark.cardBoard
        case .cardBrand: .Spark.cardBrand
        case .chain: .Spark.chain
        case .check: .Spark.check
        case .chevronHorizontalDown: .Spark.chevronHorizontalDown
        case .chevronHorizontalUp: .Spark.chevronHorizontalUp
        case .chevronVerticalLeft: .Spark.chevronVerticalLeft
        case .chevronVerticalRight: .Spark.chevronVerticalRight
        case .circleCheckFill: .Spark.circleCheckFill
        case .circleCheckOutline: .Spark.circleCheckOutline
        case .circleCrossFill: .Spark.circleCrossFill
        case .circleCrossOutline: .Spark.circleCrossOutline
        case .clickCursorFill: .Spark.clickCursorFill
        case .clickCursorOutline: .Spark.clickCursorOutline
        case .clockArrow: .Spark.clockArrow
        case .clockFill: .Spark.clockFill
        case .clockOutline: .Spark.clockOutline
        case .coinsFill: .Spark.coinsFill
        case .coinsOutline: .Spark.coinsOutline
        case .computer: .Spark.computer
        case .connectedWatch: .Spark.connectedWatch
        case .controller: .Spark.controller
        case .copyFill: .Spark.copyFill
        case .copyOutline: .Spark.copyOutline
        case .couch: .Spark.couch
        case .cradle: .Spark.cradle
        case .creditCardFill: .Spark.creditCardFill
        case .creditCardOutline: .Spark.creditCardOutline
        case .critair: .Spark.critair
        case .crop: .Spark.crop
        case .cross: .Spark.cross
        case .cursorFill: .Spark.cursorFill
        case .cursorOutline: .Spark.cursorOutline
        case .deliveryBoxFill: .Spark.deliveryBoxFill
        case .deliveryBoxOutline: .Spark.deliveryBoxOutline
        case .deliveryHandsFill: .Spark.deliveryHandsFill
        case .deliveryHandsOutline: .Spark.deliveryHandsOutline
        case .deliveryTruckFill: .Spark.deliveryTruckFill
        case .deliveryTruckOutline: .Spark.deliveryTruckOutline
        case .disconnect: .Spark.disconnect
        case .dissatisfiedFaceFill: .Spark.dissatisfiedFaceFill
        case .dissatisfiedFaceOutline: .Spark.dissatisfiedFaceOutline
        case .doubleCheck: .Spark.doubleCheck
        case .doubleChevronsLeft: .Spark.doubleChevronsLeft
        case .doubleChevronsRight: .Spark.doubleChevronsRight
        case .downloadFileFill: .Spark.downloadFileFill
        case .downloadFileOutline: .Spark.downloadFileOutline
        case .dress: .Spark.dress
        case .electricalPlug: .Spark.electricalPlug
        case .euroShieldFill: .Spark.euroShieldFill
        case .euroShieldOutline: .Spark.euroShieldOutline
        case .euroSymbol: .Spark.euroSymbol
        case .export: .Spark.export
        case .eyeFill: .Spark.eyeFill
        case .eyeOffFill: .Spark.eyeOffFill
        case .eyeOffOutline: .Spark.eyeOffOutline
        case .eyeOutline: .Spark.eyeOutline
        case .facebookLogoFill: .Spark.facebookLogoFill
        case .facebookLogoOutline: .Spark.facebookLogoOutline
        case .family: .Spark.family
        case .fileFill: .Spark.fileFill
        case .fileOffFill: .Spark.fileOffFill
        case .fileOffOutline: .Spark.fileOffOutline
        case .fileOutline: .Spark.fileOutline
        case .filter: .Spark.filter
        case .fireFill: .Spark.fireFill
        case .fireOutline: .Spark.fireOutline
        case .flagFill: .Spark.flagFill
        case .flagOutline: .Spark.flagOutline
        case .flashlightFill: .Spark.flashlightFill
        case .flashlightOutline: .Spark.flashlightOutline
        case .floorPlan: .Spark.floorPlan
        case .foldedEnvelopFill: .Spark.foldedEnvelopFill
        case .foldedEnvelopOutline: .Spark.foldedEnvelopOutline
        case .forwardFill: .Spark.forwardFill
        case .forwardOutline: .Spark.forwardOutline
        case .fountainPen: .Spark.fountainPen
        case .franceFill: .Spark.franceFill
        case .franceOutline: .Spark.franceOutline
        case .galleryFill: .Spark.galleryFill
        case .galleryOutline: .Spark.galleryOutline
        case .gameBoy: .Spark.gameBoy
        case .garage: .Spark.garage
        case .gardenTools: .Spark.gardenTools
        case .gearFill: .Spark.gearFill
        case .gearOutline: .Spark.gearOutline
        case .gift: .Spark.gift
        case .grapes: .Spark.grapes
        case .graphArrowDown: .Spark.graphArrowDown
        case .graphArrowUp: .Spark.graphArrowUp
        case .graphFill: .Spark.graphFill
        case .graphOutline: .Spark.graphOutline
        case .graphicCursor: .Spark.graphicCursor
        case .graphicHand: .Spark.graphicHand
        case .groupFill: .Spark.groupFill
        case .groupOutline: .Spark.groupOutline
        case .guitar: .Spark.guitar
        case .handGift: .Spark.handGift
        case .happyFaceFill: .Spark.happyFaceFill
        case .happyFaceOutline: .Spark.happyFaceOutline
        case .headphoneFill: .Spark.headphoneFill
        case .headphoneOutline: .Spark.headphoneOutline
        case .headphoneSmileFill: .Spark.headphoneSmileFill
        case .headphoneSmileOutline: .Spark.headphoneSmileOutline
        case .heartFill: .Spark.heartFill
        case .heartHandshake: .Spark.heartHandshake
        case .heartOutline: .Spark.heartOutline
        case .heatingHouse: .Spark.heatingHouse
        case .highlight: .Spark.highlight
        case .homeCheckFill: .Spark.homeCheckFill
        case .homeCheckOutline: .Spark.homeCheckOutline
        case .homeFill: .Spark.homeFill
        case .homeOutline: .Spark.homeOutline
        case .hotWaterdrop: .Spark.hotWaterdrop
        case .house: .Spark.house
        case .identityCardFill: .Spark.identityCardFill
        case .identityCardOutline: .Spark.identityCardOutline
        case .imageFill: .Spark.imageFill
        case .imageOutline: .Spark.imageOutline
        case .`import`: .Spark.`import`
        case .infoFill: .Spark.infoFill
        case .infoOutline: .Spark.infoOutline
        case .instagramLogoFill: .Spark.instagramLogoFill
        case .instagramLogoOutline: .Spark.instagramLogoOutline
        case .keyFill: .Spark.keyFill
        case .keyHouse: .Spark.keyHouse
        case .keyOutline: .Spark.keyOutline
        case .lamp: .Spark.lamp
        case .largeArrowUpFill: .Spark.largeArrowUpFill
        case .largeArrowUpOutline: .Spark.largeArrowUpOutline
        case .layerFill: .Spark.layerFill
        case .layerOutline: .Spark.layerOutline
        case .letterDotFill: .Spark.letterDotFill
        case .letterDotOutline: .Spark.letterDotOutline
        case .letterFill: .Spark.letterFill
        case .letterOutline: .Spark.letterOutline
        case .lightBulbFill: .Spark.lightBulbFill
        case .lightBulbOutline: .Spark.lightBulbOutline
        case .lightningFill: .Spark.lightningFill
        case .lightningOutline: .Spark.lightningOutline
        case .linkedinLogo: .Spark.linkedinLogo
        case .list: .Spark.list
        case .listItemSelected: .Spark.listItemSelected
        case .lockFill: .Spark.lockFill
        case .lockOutline: .Spark.lockOutline
        case .lockerFill: .Spark.lockerFill
        case .lockerOutline: .Spark.lockerOutline
        case .luggages: .Spark.luggages
        case .magnifierCrossFill: .Spark.magnifierCrossFill
        case .magnifierCrossOutline: .Spark.magnifierCrossOutline
        case .magnifierFill: .Spark.magnifierFill
        case .magnifierOutline: .Spark.magnifierOutline
        case .magnifierScan: .Spark.magnifierScan
        case .mailBoxCloseFill: .Spark.mailBoxCloseFill
        case .mailBoxCloseOutline: .Spark.mailBoxCloseOutline
        case .mailBoxOpenFill: .Spark.mailBoxOpenFill
        case .mailBoxOpenOutline: .Spark.mailBoxOpenOutline
        case .manWalkingFill: .Spark.manWalkingFill
        case .manWalkingOutline: .Spark.manWalkingOutline
        case .maternity: .Spark.maternity
        case .medal: .Spark.medal
        case .megaphoneFill: .Spark.megaphoneFill
        case .megaphoneMuteFill: .Spark.megaphoneMuteFill
        case .megaphoneMuteOutline: .Spark.megaphoneMuteOutline
        case .megaphoneOutline: .Spark.megaphoneOutline
        case .messengerLogo: .Spark.messengerLogo
        case .microphoneAI: .Spark.microphoneAI
        case .microphoneFill: .Spark.microphoneFill
        case .microphoneOffFill: .Spark.microphoneOffFill
        case .microphoneOffOutline: .Spark.microphoneOffOutline
        case .microphoneOutline: .Spark.microphoneOutline
        case .microwave: .Spark.microwave
        case .minus: .Spark.minus
        case .minusCircleFill: .Spark.minusCircleFill
        case .minusCircleOutline: .Spark.minusCircleOutline
        case .mobile: .Spark.mobile
        case .mobileCheck: .Spark.mobileCheck
        case .monumentFill: .Spark.monumentFill
        case .monumentOutline: .Spark.monumentOutline
        case .moonStar: .Spark.moonStar
        case .motorBike: .Spark.motorBike
        case .mouse: .Spark.mouse
        case .moveUp: .Spark.moveUp
        case .movie: .Spark.movie
        case .multimedia: .Spark.multimedia
        case .multimediaSystem: .Spark.multimediaSystem
        case .music: .Spark.music
        case .musician: .Spark.musician
        case .neutralFaceFill: .Spark.neutralFaceFill
        case .neutralFaceOutline: .Spark.neutralFaceOutline
        case .oldFill: .Spark.oldFill
        case .oldOutline: .Spark.oldOutline
        case .openLetterFill: .Spark.openLetterFill
        case .openLetterOutline: .Spark.openLetterOutline
        case .paintPalette: .Spark.paintPalette
        case .paintbrushAI: .Spark.paintbrushAI
        case .paperMapFill: .Spark.paperMapFill
        case .paperMapOutline: .Spark.paperMapOutline
        case .parasolFill: .Spark.parasolFill
        case .parasolOutline: .Spark.parasolOutline
        case .pawn: .Spark.pawn
        case .pdfFill: .Spark.pdfFill
        case .pdfOutline: .Spark.pdfOutline
        case .penFill: .Spark.penFill
        case .penOutline: .Spark.penOutline
        case .percentage: .Spark.percentage
        case .petPaw: .Spark.petPaw
        case .phoneCallEnterFill: .Spark.phoneCallEnterFill
        case .phoneCallEnterOutline: .Spark.phoneCallEnterOutline
        case .phoneCallFill: .Spark.phoneCallFill
        case .phoneCallMissFill: .Spark.phoneCallMissFill
        case .phoneCallMissOutline: .Spark.phoneCallMissOutline
        case .phoneCallOutline: .Spark.phoneCallOutline
        case .phoneCallSuccessFill: .Spark.phoneCallSuccessFill
        case .phoneCallSuccessOutline: .Spark.phoneCallSuccessOutline
        case .phoneFill: .Spark.phoneFill
        case .phoneOutline: .Spark.phoneOutline
        case .photoPack: .Spark.photoPack
        case .piggyBankFill: .Spark.piggyBankFill
        case .piggyBankOutline: .Spark.piggyBankOutline
        case .pinFill: .Spark.pinFill
        case .pinOutline: .Spark.pinOutline
        case .pinterestLogo: .Spark.pinterestLogo
        case .placeholder: .Spark.placeholder
        case .plant: .Spark.plant
        case .playFill: .Spark.playFill
        case .playOutline: .Spark.playOutline
        case .plus: .Spark.plus
        case .premiumFill: .Spark.premiumFill
        case .premiumOutline: .Spark.premiumOutline
        case .printerFill: .Spark.printerFill
        case .printerOutline: .Spark.printerOutline
        case .profileFill: .Spark.profileFill
        case .profileOutline: .Spark.profileOutline
        case .pyramid: .Spark.pyramid
        case .qRCodeScan: .Spark.qRCodeScan
        case .questionFill: .Spark.questionFill
        case .questionOutline: .Spark.questionOutline
        case .rearviewmirror: .Spark.rearviewmirror
        case .redoArrow: .Spark.redoArrow
        case .refresh: .Spark.refresh
        case .refundEuro: .Spark.refundEuro
        case .rocketFill: .Spark.rocketFill
        case .rocketOutline: .Spark.rocketOutline
        case .rotateImage: .Spark.rotateImage
        case .sadFaceFill: .Spark.sadFaceFill
        case .sadFaceOutline: .Spark.sadFaceOutline
        case .sailboat: .Spark.sailboat
        case .sandglassFill: .Spark.sandglassFill
        case .sandglassOutline: .Spark.sandglassOutline
        case .scan: .Spark.scan
        case .schoolBag: .Spark.schoolBag
        case .shareExternal: .Spark.shareExternal
        case .shareFill: .Spark.shareFill
        case .shareOutline: .Spark.shareOutline
        case .shareiOs: .Spark.shareiOs
        case .shinyBuildings: .Spark.shinyBuildings
        case .shoes: .Spark.shoes
        case .shoppingCartFill: .Spark.shoppingCartFill
        case .shoppingCartOutline: .Spark.shoppingCartOutline
        case .sort: .Spark.sort
        case .sparks: .Spark.sparks
        case .speedmeterFill: .Spark.speedmeterFill
        case .speedmeterOutline: .Spark.speedmeterOutline
        case .stack: .Spark.stack
        case .starFill: .Spark.starFill
        case .starOutline: .Spark.starOutline
        case .stopFill: .Spark.stopFill
        case .stopOutline: .Spark.stopOutline
        case .stoplight: .Spark.stoplight
        case .storeFill: .Spark.storeFill
        case .storeOutline: .Spark.storeOutline
        case .strokeImage: .Spark.strokeImage
        case .stroller: .Spark.stroller
        case .studentHat: .Spark.studentHat
        case .sun: .Spark.sun
        case .sunMoon: .Spark.sunMoon
        case .sunnyHouse: .Spark.sunnyHouse
        case .tablet: .Spark.tablet
        case .tableware: .Spark.tableware
        case .tagFill: .Spark.tagFill
        case .tagOutline: .Spark.tagOutline
        case .targetFill: .Spark.targetFill
        case .targetOutline: .Spark.targetOutline
        case .teddyBear: .Spark.teddyBear
        case .threeDimension: .Spark.threeDimension
        case .threeDimension_2: .Spark.threeDimension_2
        case .threeDotsHorizontal: .Spark.threeDotsHorizontal
        case .threeDotsVertical: .Spark.threeDotsVertical
        case .threeSixty: .Spark.threeSixty
        case .thumbDownFill: .Spark.thumbDownFill
        case .thumbDownOutline: .Spark.thumbDownOutline
        case .thumbUpFill: .Spark.thumbUpFill
        case .thumbUpOutline: .Spark.thumbUpOutline
        case .thumbtack: .Spark.thumbtack
        case .ticket: .Spark.ticket
        case .tractor: .Spark.tractor
        case .trainFill: .Spark.trainFill
        case .trainOutline: .Spark.trainOutline
        case .trashCrossFill: .Spark.trashCrossFill
        case .trashCrossOutline: .Spark.trashCrossOutline
        case .trashFill: .Spark.trashFill
        case .trashOutline: .Spark.trashOutline
        case .treeFence: .Spark.treeFence
        case .truckClockFill: .Spark.truckClockFill
        case .truckClockOutline: .Spark.truckClockOutline
        case .tshirt: .Spark.tshirt
        case .twitterLogo: .Spark.twitterLogo
        case .undoArrow: .Spark.undoArrow
        case .unlockFill: .Spark.unlockFill
        case .unlockOutline: .Spark.unlockOutline
        case .userCheckFill: .Spark.userCheckFill
        case .userCheckOutline: .Spark.userCheckOutline
        case .userCircleFill: .Spark.userCircleFill
        case .userCircleOutline: .Spark.userCircleOutline
        case .userFill: .Spark.userFill
        case .userOutline: .Spark.userOutline
        case .utilityTruck: .Spark.utilityTruck
        case .vase: .Spark.vase
        case .verifiedShieldFill: .Spark.verifiedShieldFill
        case .verifiedShieldOutline: .Spark.verifiedShieldOutline
        case .walletBrand: .Spark.walletBrand
        case .warningFill: .Spark.warningFill
        case .warningImage: .Spark.warningImage
        case .warningOutline: .Spark.warningOutline
        case .warningShieldFill: .Spark.warningShieldFill
        case .warningShieldOutline: .Spark.warningShieldOutline
        case .watch: .Spark.watch
        case .waterdrop: .Spark.waterdrop
        case .whatsappLogo: .Spark.whatsappLogo
        case .wifi: .Spark.wifi
        case .workFill: .Spark.workFill
        case .workOutline: .Spark.workOutline
        case .wrench: .Spark.wrench
        }
    }
}
